package CondoWare2;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EmpresasParceiras extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private EmpresasParceiras() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private static EmpresasParceiras empresasParceirasUnic;
    public static EmpresasParceiras getEmpresasParceirasUnic(){
        if(empresasParceirasUnic == null){
            empresasParceirasUnic = new EmpresasParceiras();
        }
        return empresasParceirasUnic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabEmpresas = new javax.swing.JTable();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empresas Parceiras");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tabEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome da Empresa", "Contato", "Responsável", "Serviço"
            }
        ));
        tabEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabEmpresasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabEmpresas);

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btVoltar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarAll();
    }//GEN-LAST:event_formWindowActivated

    private void tabEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabEmpresasMouseClicked
        mostrarLinha();
    }//GEN-LAST:event_tabEmpresasMouseClicked

    public void listarAll() {
        Bancos.getBancos().getBdEmpresas().clear();
        Conexao.getConexao().atualizaBancoEmpresa();
        DefaultTableModel tabModel = (DefaultTableModel) tabEmpresas.getModel();
        int posLin = 0;
        tabModel.setRowCount(posLin);
        for(Empresas e: Bancos.getBancos().getBdEmpresas()) {
            tabModel.insertRow(posLin, new Object[]{e.getNome(),
                                                       e.getContato(),
                                                       e.getResponsavel(),
                                                       e.getServico()});
            posLin++;
        }
    }
    
    public void mostrarLinha(){
        int row = tabEmpresas.getSelectedRow();
        String nome = (String) tabEmpresas.getValueAt(row, 0);
        String contato = (String) tabEmpresas.getValueAt(row,1);
        String responsavel = (String) tabEmpresas.getValueAt(row,2);
        String servico = (String) tabEmpresas.getValueAt(row,3);
        JOptionPane.showMessageDialog(
                        null,
                        "Nome: " +nome+
                        "\nContato: " +contato+
                        "\nResponsável: " +responsavel+
                        "\nServiço: "+servico,
                        "Dados da Empresa",
                        1);
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabEmpresas;
    // End of variables declaration//GEN-END:variables
}
