package CondoWare2;

import static java.lang.constant.ConstantDescs.NULL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegistrarVisitante extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarVisitante
     */
    private RegistrarVisitante() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private static RegistrarVisitante registrarVisitanteUnic;
    public static RegistrarVisitante getRegistrarVisitanteUnic(){
        if(registrarVisitanteUnic == null){
            registrarVisitanteUnic = new RegistrarVisitante();
        }
        return registrarVisitanteUnic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotMsgEnt = new javax.swing.JLabel();
        rotNome = new javax.swing.JLabel();
        rotAp = new javax.swing.JLabel();
        rotBloco = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxApartamento = new javax.swing.JTextField();
        cxBloco = new javax.swing.JTextField();
        rotMsgSaida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabEntradaVis = new javax.swing.JTable();
        btRegistroEnt = new javax.swing.JButton();
        btRegistroSaida = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Visitantes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        rotMsgEnt.setText("Entrada de Visitante");

        rotNome.setText("Nome:");

        rotAp.setText("Apartamento:");

        rotBloco.setText("Bloco:");

        rotMsgSaida.setText("Registro de Saida");

        tabEntradaVis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Apartamento", "Bloco"
            }
        ));
        jScrollPane1.setViewportView(tabEntradaVis);

        btRegistroEnt.setText("Registrar Entrada");
        btRegistroEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroEntActionPerformed(evt);
            }
        });

        btRegistroSaida.setText("Registrar Saida");
        btRegistroSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroSaidaActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btHistorico.setText("Historico");
        btHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btVoltar)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(btRegistroEnt))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btHistorico)
                                        .addGap(18, 18, 18)
                                        .addComponent(btRegistroSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rotAp)
                                            .addComponent(rotBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rotNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxNome))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(rotMsgEnt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(rotMsgSaida)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotMsgEnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotAp)
                    .addComponent(cxApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotBloco)
                    .addComponent(cxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRegistroEnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotMsgSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegistroSaida)
                    .addComponent(btVoltar)
                    .addComponent(btHistorico))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        limpar();
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btRegistroEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroEntActionPerformed
       int res = Conexao.getConexao().registraEntradaVisitante(cxNome.getText(), Integer.parseInt(cxBloco.getText()), Integer.parseInt(cxApartamento.getText()));;
        if(res == 1) {
            JOptionPane.showMessageDialog(
                        null,
                        "Entrada de visitante Registrada",
                        "Visitante",
                        1);
            listarAll();
        }
        else {
            JOptionPane.showMessageDialog(
                        null,
                        "Ocorreu um erro ao registrar entrada do visitante!",
                        "Visitante",
                        0);                                       
        } 
        listarAll();
        limpar();
    }//GEN-LAST:event_btRegistroEntActionPerformed

    private void btRegistroSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroSaidaActionPerformed
        int row = tabEntradaVis.getSelectedRow();      
        String nome = tabEntradaVis.getValueAt(row, 0).toString();
        int bloco = (int) tabEntradaVis.getValueAt(row, 2);
        int apartamento = (int) tabEntradaVis.getValueAt(row, 1);       
        int res = Conexao.getConexao().registraSaidaVisitante(nome, bloco, apartamento);
        if(res == 1) {
            JOptionPane.showMessageDialog(
                        null,
                        "Saída do visitante registrado com sucesso",
                        "Visitante",
                        1);
        }
        else {
            JOptionPane.showMessageDialog(
                        null,
                        "Ocorreu um erro ao registrar saída do visitante!",
                        "Visitante",
                        0);
        }
    }//GEN-LAST:event_btRegistroSaidaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarAll();
    }//GEN-LAST:event_formWindowActivated

    private void btHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistoricoActionPerformed
        HistoricoVisitas.getHistoricoVisitasUnic().setVisible(true);
    }//GEN-LAST:event_btHistoricoActionPerformed
    
    public void listarAll() {
        Conexao.getConexao().atualizaBancoVisitante();
        DefaultTableModel tabModel = (DefaultTableModel) tabEntradaVis.getModel();
        int posLin = 0;
        tabModel.setRowCount(posLin);
        for(int i = 0; i < Bancos.getBancos().bdVisitante.size(); i++){
            if(Bancos.getBancos().getBdVisitante().get(i).getSaida() == null){
                tabModel.insertRow(posLin, new Object[]{Bancos.getBancos().bdVisitante.get(i).getNomeVisitante(),
                                                           Bancos.getBancos().bdVisitante.get(i).getApVisitado(),
                                                           Bancos.getBancos().bdVisitante.get(i).getBlocoVisitado()});
                posLin++;
            }
        }
    }
    
    public void limpar(){
        cxNome.setText("");
        cxApartamento.setText("");
        cxBloco.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHistorico;
    private javax.swing.JButton btRegistroEnt;
    private javax.swing.JButton btRegistroSaida;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField cxApartamento;
    private javax.swing.JTextField cxBloco;
    private javax.swing.JTextField cxNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotAp;
    private javax.swing.JLabel rotBloco;
    private javax.swing.JLabel rotMsgEnt;
    private javax.swing.JLabel rotMsgSaida;
    private javax.swing.JLabel rotNome;
    private javax.swing.JTable tabEntradaVis;
    // End of variables declaration//GEN-END:variables
}
