package CondoWare2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RelatorioLazer extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioLazer
     */
    private RelatorioLazer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private static RelatorioLazer relatorioLazerUnic;
    public static RelatorioLazer getRelatorioLazerUnic() {
        if (relatorioLazerUnic == null) {
            relatorioLazerUnic = new RelatorioLazer();
        }
        return relatorioLazerUnic;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabAreasDeLazer = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();
        btApagar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela Areas de Lazer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tabAreasDeLazer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Capacidade", "Aluguel"
            }
        ));
        jScrollPane1.setViewportView(tabAreasDeLazer);

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btApagar.setText("Apagar");
        btApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btVoltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btApagar)
                    .addComponent(btEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if(tabAreasDeLazer.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(
                    null,
                    "Selecione alguma área de lazer na tabela!!",
                    "Atenção!!",
                    1);
        }
        else{
            int row = tabAreasDeLazer.getSelectedRow();
            EditLazer.getEditLazerUnic().receberLazer((String)tabAreasDeLazer.getValueAt(row,0),(int)tabAreasDeLazer.getValueAt(row,1),(float) tabAreasDeLazer.getValueAt(row,2));
            EditLazer.getEditLazerUnic().setVisible(true);
        }
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void btApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarActionPerformed
        if(tabAreasDeLazer.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(
                    null,
                    "Selecione alguma área de lazer na tabela!!",
                    "Atenção!!",
                    1);
        }
        else{
            int row = tabAreasDeLazer.getSelectedRow();
            ApagarLazer.getApagarLazerUnic().receberLazer((String)tabAreasDeLazer.getValueAt(row,0),(int)tabAreasDeLazer.getValueAt(row,1),(float) tabAreasDeLazer.getValueAt(row,2));
            ApagarLazer.getApagarLazerUnic().setVisible(true);
        }
    }//GEN-LAST:event_btApagarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarAll();
    }//GEN-LAST:event_formWindowActivated

    public void listarAll() {
        Bancos.getBancos().getBdAreaDeLazer().clear();
        Conexao.getConexao().atualizaBancoAreaDeLazer();
        DefaultTableModel tabModel = (DefaultTableModel) tabAreasDeLazer.getModel();
        int posLin = 0;
        tabModel.setRowCount(posLin);
        for(AreaDeLazer a: Bancos.getBancos().getBdAreaDeLazer()) {
            tabModel.insertRow(posLin, new Object[]{a.getTipo(),
                                                       a.getCapacidade(),
                                                       a.getValor()});
            posLin++;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApagar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabAreasDeLazer;
    // End of variables declaration//GEN-END:variables
}
